#!/bin/bash


function err {
    echo "ERROR: $@"
}

function help {
    echo "Usage:"
    echo "    yt-playlist-sync PLAYLIST_PATH PLAYLIST_URL"
}


#PERSONAL DEFAULTS
plUrl="https://www.youtube.com/playlist?list=PLOoJ3WlgcZEyUhfpaLKzngtxOh2aV__ye"
plPath=/home/salamon/down/music/watchLaterHistory-sync
youParsePath="youParse/youParse.py"

if [[ $1 == "" || $2 == "" ]]; then
    err "Expecting 2 arguments"
    help
    exit 1
fi

plPath="$1"
plUrl="$2"

if [[ ! -d "$plPath" ]]; then
    err "Directory does not exist - $plPath"
    help
    exit 2
fi


localUrls="$plPath/.urls"
remoteUrls="$plPath/.urls-remote"
diffUrls="$plPath/.urls-diff"


if [[ ! -f "$localUrls" ]]; then
    touch "$localUrls"
fi

if ! python3 "$youParsePath" "$plUrl" | sort > "$remoteUrls"; then
    err "Youtube playlist url is not vaild - $plUrl"
    help
    exit 3
fi
    

tmpFile=`mktemp /tmp/yt-playlist-sync-XXX.tmp`
cat "$localUrls" | sort > "$tmpFile"
cat "$tmpFile" > "$localUrls"
rm "$tmpFile"

comm -13 "$localUrls" "$remoteUrls" > "$diffUrls"

echo "Downloading `cat $diffUrls | wc -l` new songs!"

cnt=0
while read u; do
    echo "Downloading $u"
    if youtube-dl --audio-format mp3 -x -o "$plPath/%(title)s.%(ext)s" "$u"
    then
        echo "Success!"
        echo "$u" >> "$localUrls"
        cnt=$(($cnt+1))
        # delete all webm files from previous runs after first success
        # keeps progress between two conscutive runs
        rm "$plPath"/*.webm 2>/dev/null 
    else
        echo "Fail!"
        # let's you kill program with double Ctrl-C
        sleep 1
    fi
done < "$diffUrls"

echo "Downloaded $cnt out of `cat $diffUrls | wc -l` new songs!"


