#!/bin/bash

#FUNCTIONS
function err 
{
	printf "$0 [ERROR]: %s\n" "$1" >&2
	if [[ "$2" == "help" ]]
	then
		help
		exit "$3"
	else
		exit "$2"
	fi
}

function help 
{
    printf "$0 [USAGE]: yt-playlist-sync PLAYLIST_PATH PLAYLIST_URL [-v]\n"
}

#KEY VARIABLES
ytDlTimeout=60
youParsePath="youParse/youParse.py"

plPath="$1"
plUrl="$2"

localUrls="$plPath/.urls"
remoteUrls="$plPath/.urls-remote"
diffUrls="$plPath/.urls-diff"
backupUrls="$plPath/.urls.bak"

#INPUT VERIFICATION
[[ "$#" -lt 2 ]] && err "Expecting at least 2 arguments" "help" 1

[[ ! -d "$plPath" ]] && err "Directory does not exist - $plPath" "help" 2

[[ ! -f "$localUrls" ]] && touch "$localUrls"

if ! python3 "$youParsePath" "$plUrl" | sort > "$remoteUrls"
then
    err "Youtube playlist url is not vaild - $plUrl" "help" 3
fi

#CORE
if ! diff "$localUrls" "$backupUrls" -q; then
    cat "$localUrls" "$backupUrls" | sort -u >> tee "/dev/null" "$localUrls" "$backupUrls" >/dev/null
fi
cat "$localUrls" | sort | tee "/dev/null" "$localUrls" >/dev/null
comm -13 "$localUrls" "$remoteUrls" > "$diffUrls"
printf "Downloading `cat $diffUrls | wc -l` new songs!\n"

cnt=0
while read u; do
    printf "Downloading %s\n" "$u"
    devnull=">/dev/null 2>/dev/null"
    [[ "$3" != "-v" ]] && devnull=""
    if timeout "$ytDlTimeout" youtube-dl --audio-format mp3 -x -o "$plPath/%(title)s.%(ext)s" "$u" $devnull
    then
        echo "Success!"
        printf "$u\n" >> "$localUrls"
        cp "$localUrls" "$backupUrls" 
        cnt=$(($cnt+1))
        # delete all webm files from previous runs after first success
        # keeps progress between two conscutive runs
        rm "$plPath"/*.webm 2>/dev/null 
    else
        echo "Fail!"
        # let's you kill program with double Ctrl-C
        sleep 1
    fi
done < "$diffUrls"

printf "Downloaded $cnt out of `cat $diffUrls | wc -l` new songs!"

exit 0
